### ISSUE TITLE
Login page layout

### ISSUE THREAD

**Issue by loadevent** [loadevent/countryclub#1]
- [x] add css and js files
- [x] add images folder
- [x] create login layout for login view
- [x] create login page / view

**Comment by loadevent** [comment]
page created, looks good

**Comment by loadevent** [comment]
looks good
